storage:

  type: LOCAL


  local:

    root-path: ${BLOG_STORAGE_ROOT:./blog-storage}

    domain: ${BLOG_FILE_DOMAIN:http://localhost:${SERVER_PORT:5090}/files}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

  configuration:
    map-underscore-to-camel-case: true
