spring.application.name=demo_bk

spring.config.import=optional:file:.env[.properties],optional:file:demo_bk/.env[.properties]
server.port=${SERVER_PORT:5090}

# sql
spring.datasource.url=${BLOG_DB_URL:jdbc:mysql://127.0.0.1:3306/white_jotter?characterEncoding=utf8}
spring.datasource.username=${BLOG_DB_USERNAME:}
spring.datasource.password=${BLOG_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = none

# Redis
spring.data.redis.host=${BLOG_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${BLOG_REDIS_PORT:6379}
spring.data.redis.database=${BLOG_REDIS_DATABASE:0}
spring.data.redis.timeout=5000ms

spring.data.redis.password=${BLOG_REDIS_PASSWORD:}

# JWT
blog.jwt.secret=${BLOG_JWT_SECRET:}

# Lettuce connection pool
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=1000ms
