storage:

  type: LOCAL


  local:

    root-path: ./blog-storage

    domain: http://localhost:5090/files

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

  configuration:
    map-underscore-to-camel-case: true
